# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(max_length=15)),
                ('nominal', models.IntegerField(null=True)),
                ('jenis_gaji', models.CharField(choices=[('bulan', 'bulan'), ('hari', 'hari'), ('jam', 'jam')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_user', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=30)),
                ('username', models.CharField(blank=True, max_length=15)),
                ('tgl_lahir', models.DateField(default=1994)),
                ('alamat_skr', models.CharField(max_length=75)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Jabatan')),
            ],
        ),
    ]
