# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='status_user',
            field=models.BooleanField(default=False),
        ),
    ]
