# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_status_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='kd_user',
        ),
        migrations.AddField(
            model_name='profiles',
            name='kd_profile',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
