# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170614_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='tgl_lahir',
            field=models.DateField(default=datetime.date(2017, 6, 16)),
        ),
    ]
