# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170617_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='tgl_lahir',
            field=models.DateField(default=datetime.date(2017, 6, 18)),
        ),
    ]
