# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_item', models.CharField(max_length=15)),
                ('nama', models.CharField(max_length=25)),
                ('harga', models.PositiveIntegerField()),
                ('deskripsi', models.TextField(blank=True)),
                ('stok', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='JenisItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='jenis_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.JenisItem'),
        ),
    ]
