# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170617_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=b'')),
                ('nama', models.CharField(max_length=25)),
                ('harga', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='harga',
            new_name='jumlah',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stok',
        ),
        migrations.AddField(
            model_name='menu',
            name='item',
            field=models.ForeignKey(help_text='Item utama yang digunakan', on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
