# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20170617_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='id',
        ),
        migrations.AddField(
            model_name='menu',
            name='kd_menu',
            field=models.CharField(default=1, max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
