# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20170618_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='deskripsi',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
