# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_auto_20170617_0620'),
        ('profiles', '0005_auto_20170617_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiKeluar',
            fields=[
                ('kd_keluar', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('tgl_keluar', models.DateTimeField(default=datetime.datetime(2017, 6, 17, 7, 16, 1, 953942))),
                ('harga', models.PositiveIntegerField()),
                ('jumlah', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiMasuk',
            fields=[
                ('kd_masuk', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('tgl_masuk', models.DateTimeField(default=datetime.datetime(2017, 6, 17, 7, 16, 1, 952849))),
                ('jumlah', models.PositiveIntegerField()),
                ('bayar', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profiles')),
            ],
        ),
    ]
