# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksikeluar',
            name='tgl_keluar',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 17, 23, 21, 15, 123620)),
        ),
        migrations.AlterField(
            model_name='transaksimasuk',
            name='tgl_masuk',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 17, 23, 21, 15, 122768)),
        ),
    ]
