# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0002_auto_20170617_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksikeluar',
            name='tgl_keluar',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 18, 20, 0, 14, 770900)),
        ),
        migrations.AlterField(
            model_name='transaksimasuk',
            name='tgl_masuk',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 18, 20, 0, 14, 770169)),
        ),
    ]
