# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0003_auto_20170618_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksikeluar',
            name='tgl_keluar',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 19, 2, 6, 43, 988535)),
        ),
        migrations.AlterField(
            model_name='transaksimasuk',
            name='tgl_masuk',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 19, 2, 6, 43, 987655)),
        ),
    ]
